language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk15

cache:
  directories:
    - $HOME/.m2

arch:
  - ppc64le

before_install: 
   - mkdir -p /opt/maven
   - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven
   - export MAVEN_HOME=/opt/maven
   - export PATH=${MAVEN_HOME}/bin:${PATH}

script:
  - mvn -V --no-transfer-progress
